# Generated by Django 5.1.4 on 2025-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tags',
            field=models.CharField(default='Posts.', max_length=255),
        ),
    ]
