# Generated by Django 5.0.7 on 2024-07-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startBlog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
