# Generated by Django 5.1.4 on 2025-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startBlog', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
